- name: Update Prod Job template
  tower_job_template:
    name: "{{ item.value.name }}"
    credential: "{{ credential }}"
    tower_host: "tower1.{{ tower_guid }}.example.opentlc.com"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl }}"
    state: present
    job_type: run
    playbook: "{{ item.value.playbook }}"
    project: "{{ proj_name }}"
  with_dict: "{{ templates }}"

