---

- name: ensure {{ payload }} is at the latest level
  yum:
    name: "{{ payload }}"
    state: latest

- name: ensure {{ payload }} is enabled at boot
  service:
    name: "{{ payload }}"
    enabled: yes

- name: configure {{ payload }} to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf_dir }}/haproxy.cfg"
    mode: 0644
  notify:
    - restart {{ payload }}

- name: ensure {{ payload }} is running
  service:
    name: "{{ payload }}"
    state: started


