---
- name: Ensure {{ payload }} is at the lastest level
  yum:
    name: "{{ payload }}"
    state: latest

- name: Ensure {{ payload }} is enabled at boot
  service:
    name: "{{ payload }}"
    enabled: yes

- name: Create {{ payload }} default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory
  notify:
    - Restart {{ payload }}

- name: Copy static index.html to {{ payload }} webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify:
    - Restart {{ payload }}

- name: Ensure {{ payload }} is running
  service:
    name: "{{ payload }}"
    state: started


